[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
